(function(window){

	var bodyd = [];
	bodyd[0] =  '';
	bodyd[1] = 'The muscular system is an organ system consisting of skeletal, smooth and cardiac muscles. It permits movement of the body, maintains posture, and circulates blood throughout the body. The muscular system in vertebrates is controlled through the nervous system, although some muscles (such as the cardiac muscle) can be completely autonomous. Together with the skeletal system it forms the musculoskeletal system, which is responsible for movement of the human body.';
	bodyd[2] = 'The human skeleton is the internal framework of the body. It is composed of 270 bones at birth – this total decreases to 206 bones by adulthood after some bones have fused together.[1] The bone mass in the skeleton reaches maximum density around age 30. The human skeleton can be divided into the axial skeleton and the appendicular skeleton. The axial skeleton is formed by the vertebral column, the rib cage and the skull. The appendicular skeleton, which is attached to the axial skeleton, is formed by the pectoral girdle, the pelvic girdle and the bones of the upper and lower limbs.';
	bodyd[3] = 'The nervous system is the part of an animal"s body that coordinates its voluntary and involuntary actions and transmits signals between different parts of its body. Nervous tissue first arose in wormlike organisms about 550 to 600 million years ago. In most animal species it consists of two main parts, the central nervous system (CNS) and the peripheral nervous system (PNS). The CNS contains the brain and spinal cord. The PNS consists mainly of nerves, which are enclosed bundles of the long fibers or axons, that connect the CNS to every other part of the body. The PNS includes motor neurons, mediating voluntary movement; the autonomic nervous system, comprising the sympathetic nervous system and the parasympathetic nervous system, which regulate involuntary functions, and the enteric nervous system, which functions to control the gastrointestinal system.';
	bodyd[4] = 'The circulatory system, also called the cardiovascular system, is an organ system that permits blood to circulate and transport nutrients (such as amino acids and electrolytes), oxygen, carbon dioxide, hormones, and blood cells to and from the cells in the body to provide nourishment and help in fighting diseases, stabilize temperature and pH, and maintain homeostasis. The study of the blood flow is called hemodynamics. The study of the properties of the blood flow is called hemorheology';
	bodyd[5] = 'The urinary system, also known as the renal system, consists of the two kidneys, ureters, the bladder, and the urethra. Each kidney consists of millions of functional units called nephrons. The purpose of the renal system is to eliminate wastes from the body, regulate blood volume and pressure, control levels of electrolytes and metabolites, and regulate blood pH. The kidneys have extensive blood supply via the renal arteries which leave the kidneys via the renal vein. Following filtration of blood and further processing, wastes (in the form of urine) exit the kidney via the ureters, tubes made of smooth muscle fibers that propel urine towards the urinary bladder, where it is stored and subsequently expelled from the body by urination (voiding). The female and male urinary system are very similar, differing only in the length of the urethra.';
	bodyd[6] = 'In the human digestive system, the process of digestion has many stages, the first of which starts in the mouth (oral cavity). Digestion involves the breakdown of food into smaller and smaller components which can be absorbed and assimilated into the body. The secretion of saliva helps to produce a bolus which can be swallowed to pass down the oesophagus and into the stomach.';
	

	var bodydata = {

'cardiovascularsystem':'The circulatory system, also called the cardiovascular system, is an organ system that permits blood to circulate and transport nutrients (such as amino acids and electrolytes), oxygen, carbon dioxide, hormones, and blood cells to and from the cells in the body to provide nourishment and help in fighting diseases, stabilize temperature and pH, and maintain homeostasis. The study of the blood flow is called hemodynamics. The study of the properties of the blood flow is called hemorheology',

'vesselsoftheheadandneck':'Head and neck anatomy focuses on the structures of the head and neck of the human body, including the brain, bones, muscles, blood vessels, nerves, glands, nose, mouth, teeth, tongue, and throat. It is an area frequently studied in depth by surgeons, dentists, dental technicians, and speech language pathologists.',

'vesselsoftheupperlimb':'The upper limb or upper extremity is the region in an animal extending from the deltoid region to the hand, including the arm, axilla and shoulder.',

'vesselsofthethroaxandheart':'The heart is a muscular organ in humans and other animals, which pumps blood through the blood vessels of the circulatory system.[1] Blood provides the body with oxygen and nutrients, and also assists in the removal of metabolic wastes.[2] The heart is located in the middle compartment of the mediastinum in the chest.',

'vesselsoftheabdomen':'Abdomen (less formally called the belly, stomach, tummy or midriff) constitutes the part of the body between the thorax (chest) and pelvis: in humans and in other vertebrates such as mammals. The region enclosed by the abdomen is termed the abdominal cavity. In arthropods it is the posterior tagma of the body; it follows the thorax or cephalothorax.[1][2] Anatomically, the abdomen stretches from the thorax at the thoracic diaphragm to the pelvis at the pelvic brim. The pelvic brim stretches from the lumbosacral angle (the intervertebral disk between L5 and S1) to the pubic symphysis and is the edge of the pelvic inlet. The space above this inlet and under the thoracic diaphragm is termed the abdominal cavity. The boundary of the abdominal cavity is the abdominal wall in the front and the peritoneal surface at the rear.',

'vesselsofthepelvis':'In human anatomy, the pelvis (plural pelves or pelvises) is either the lower part of the trunk,[1] between the abdomen and the thighs (sometimes also called pelvic region of the trunk), or the skeleton embedded in it[2] (sometimes also called bony pelvis, or pelvic skeleton).',

'vesselsofthelowerlimb':'The human leg is the entire lower extremity or limb of the human body, including the foot, thigh and even the hip or gluteal region; however, the precise definition in human anatomy refers[3][4][5] only to the section of the lower limb extending from the knee to the ankle (called "crus" in Latin or "sura" for the backpart).',

"digestivesystem":'In the human digestive system, the process of digestion has many stages, the first of which starts in the mouth (oral cavity). Digestion involves the breakdown of food into smaller and smaller components which can be absorbed and assimilated into the body. The secretion of saliva helps to produce a bolus which can be swallowed to pass down the oesophagus and into the stomach.',

"bileducts": 'A bile duct is any of a number of long tube-like structures that carry bile.',

"gallbladder":'In vertebrates the gallbladder (also gall bladder, biliary vesicle or cholecyst), is a small organ where bile (a fluid produced by the liver) is stored and concentrated before it is released into the small intestine. Humans can live without a gallbladder. The surgical removal of the gallbladder is called a cholecystectomy.',

"gastrointestinaltract": 'Digestion is the breakdown of large insoluble food molecules into small water-soluble food molecules so that they can be absorbed into the watery blood plasma. In certain organisms, these smaller substances are absorbed through the small intestine into the blood stream. Digestion is a form of catabolism that is often divided into two processes based on how food is broken down: mechanical and chemical digestion. The term mechanical digestion refers to the physical breakdown of large pieces of food into smaller pieces which can subsequently be accessed by digestive enzymes. In chemical digestion, enzymes break down food into the small molecules the body can use.',


"liver": 'The liver is a vital organ of vertebrates and some other animals. In the human it is located in the upper right quadrant of the abdomen, below the diaphragm. The liver has a wide range of functions, including detoxification of various metabolites, protein synthesis, and the production of biochemicals necessary for digestion. There is currently no way to compensate for the absence of liver function in the long term, although liver dialysis techniques can be used in the short term.',

"pancreas":'The pancreas  is a glandular organ in the digestive system and endocrine system of vertebrates. In humans, it is located in the abdominal cavity behind the stomach. It is an endocrine gland producing several important hormones, including insulin, glucagon, somatostatin, and pancreatic polypeptide which circulate in the blood. The pancreas is also a digestive organ, secreting pancreatic juice containing digestive enzymes that assist digestion and absorption of nutrients in the small intestine. These enzymes help to further break down the carbohydrates, proteins, and lipids in the chyme.',


"leftsalivaryglands": 'The salivary glands in mammals are exocrine glands, glands with ducts, that produce saliva. They also secrete amylase, an enzyme that breaks down starch into maltose.',

"rightsalivaryglands": 'The salivary glands in mammals are exocrine glands, glands with ducts, that produce saliva. They also secrete amylase, an enzyme that breaks down starch into maltose.',


"endocrinesystem":'The endocrine system refers to the collection of glands of an organism that secrete hormones directly into the circulatory system to be carried towards distant target organs. The major endocrine glands include the pineal gland, pituitary gland, pancreas, ovaries, testes, thyroid gland, parathyroid gland, hypothalamus, gastrointestinal tract and adrenal glands. The endocrine system is in contrast to the exocrine system, which secretes its hormones using ducts. The endocrine system is an information signal system like the nervous system, yet its effects and mechanism are classifiably different. The endocrine system"s effects are slow to initiate, and prolonged in their response, lasting from a few hours up to weeks. The nervous system sends information very quickly, and responses are generally short lived. In vertebrates, the hypothalamus is the neural control center for all endocrine systems. The field of study dealing with the endocrine system and its disorders is endocrinology, a branch of internal medicine.',

"leftadrenalgland":'The adrenal glands (also known as suprarenal glands) are endocrine glands that produce a wide variety of hormones.[1] They are found on the top of the kidneys and consist of a number of different layers that directly influence the structure and function of the glands. Each gland has an outer cortex made of steroid-producing cells surrounding a core of medulla, formed by chromaffin cells in direct relationship with the sympathetic nervous system. The adrenal cortex is divided into three zones according to their functions and microscopic appearance.',

"rightadrenalgland":'The adrenal glands (also known as suprarenal glands) are endocrine glands that produce a wide variety of hormones.[1] They are found on the top of the kidneys and consist of a number of different layers that directly influence the structure and function of the glands. Each gland has an outer cortex made of steroid-producing cells surrounding a core of medulla, formed by chromaffin cells in direct relationship with the sympathetic nervous system. The adrenal cortex is divided into three zones according to their functions and microscopic appearance.',

"parathyroidglands":'The parathyroid glands are small endocrine glands in the neck of humans and other tetrapods that produce parathyroid hormone. Humans usually have four parathyroid glands, variably located on the back of the thyroid gland, although considerable variation exists.[1] Parathyroid hormone and calcitonin (one of the hormones made by the thyroid gland) have key roles in regulating the amount of calcium in the blood and within the bones.',

"thyroidgland":'The thyroid gland, or simply the thyroid , in vertebrate anatomy, is one of the largest endocrine glands and consists of two connected lobes. The thyroid gland is found in the neck, below the thyroid cartilage (which forms the laryngeal prominence, or "Adam"s apple"). The thyroid gland controls how quickly the body uses energy, makes proteins, and controls how sensitive the body is to other hormones. It participates in these processes by producing thyroid hormones, the principal ones being triiodothyronine (T3) and thyroxine (sometimes referred to as tetraiodothyronine (T4)). These hormones regulate the growth and rate of function of many other systems in the body. T3 and T4 are synthesized from iodine and tyrosine. The thyroid also produces calcitonin, which plays a role in calcium homeostasis.',

"ligaments": 'In anatomy, a ligament is the fibrous connective tissue that connects bones to other bones and is also known as articular ligament, articular larua,[1] fibrous ligament, or true ligament.',

"ligamentsoftheheadandneck":'Head and neck anatomy focuses on the structures of the head and neck of the human body, including the brain, bones, muscles, blood vessels, nerves, glands, nose, mouth, teeth, tongue, and throat. It is an area frequently studied in depth by surgeons, dentists, dental technicians, and speech language pathologists.',

"ligamentsoftheupperlimb":'The upper limb or upper extremity is the region in an animal extending from the deltoid region to the hand, including the arm, axilla and shoulder.',

"ligamentsofthethorax":'The thorax or chest (Greek: θώραξ, Latin: thorax) is a part of the anatomy of humans and various other animals located between the neck and the abdomen. The thorax includes the thoracic cavity and the thoracic wall. It contains organs including the heart, lungs and thymus gland, as well as muscles and various other internal structures. Many diseases may affect the chest, and one of the most common symptoms is chest pain.',

"ligamentsofthepelvis":'In human anatomy, the pelvis (plural pelves or pelvises) is either the lower part of the trunk, between the abdomen and the thighs (sometimes also called pelvic region of the trunk), or the skeleton embedded in it (sometimes also called bony pelvis, or pelvic skeleton.',

"ligamentsofthelowerlimb": 'The human leg is the entire lower extremity or limb of the human body, including the foot, thigh and even the hip or gluteal region; however, the precise definition in human anatomy refers only to the section of the lower limb extending from the knee to the ankle (called "crus" in Latin or "sura" for the backpart).',


"lymphaticsystem": 'The lymphatic system is part of the circulatory system, comprising a network of lymphatic vessels that carry a clear fluid called lymph (from Latin lympha meaning water) directionally towards the heart. The lymphatic system was first described in the seventeenth century independently by Olaus Rudbeck and Thomas Bartholin. Unlike the cardiovascular system the lymphatic system is not a closed system. The human circulatory system processes an average of 20 litres of blood per day through capillary filtration which removes plasma while leaving the blood cells. Roughly 17 litres of the filtered plasma get reabsorbed directly into the blood vessels, while the remaining 3 litres are left behind in the interstitial fluid. One of the main functions of the lymph system is to provide an accessory return route to the blood for the surplus 3 litres.',

"lymphaticsoftheheadandneck":'Head and neck anatomy focuses on the structures of the head and neck of the human body, including the brain, bones, muscles, blood vessels, nerves, glands, nose, mouth, teeth, tongue, and throat. It is an area frequently studied in depth by surgeons, dentists, dental technicians, and speech language pathologists.',

"lymphaticsoftheupperlimb":'The upper limb or upper extremity is the region in an animal extending from the deltoid region to the hand, including the arm, axilla and shoulder.',

"lymphaticsofthethorax":'The thorax or chest (Greek: θώραξ, Latin: thorax) is a part of the anatomy of humans and various other animals located between the neck and the abdomen. The thorax includes the thoracic cavity and the thoracic wall. It contains organs including the heart, lungs and thymus gland, as well as muscles and various other internal structures. Many diseases may affect the chest, and one of the most common symptoms is chest pain.',

"lymphaticsoftheabdomenandpelvis":'In human anatomy, the pelvis (plural pelves or pelvises) is either the lower part of the trunk, between the abdomen and the thighs (sometimes also called pelvic region of the trunk), or the skeleton embedded in it (sometimes also called bony pelvis, or pelvic skeleton).',

"lymphaticsofthelowerlimb":'The human leg is the entire lower extremity or limb[1][2] of the human body, including the foot, thigh and even the hip or gluteal region; however, the precise definition in human anatomy refers[3][4][5] only to the section of the lower limb extending from the knee to the ankle (called "crus" in Latin or "sura" for the backpart).',

"nervoussystem": 'The nervous system is the part of an animal"s body that coordinates its voluntary and involuntary actions and transmits signals between different parts of its body. Nervous tissue first arose in wormlike organisms about 550 to 600 million years ago. In most animal species it consists of two main parts, the central nervous system (CNS) and the peripheral nervous system (PNS). The CNS contains the brain and spinal cord. The PNS consists mainly of nerves, which are enclosed bundles of the long fibers or axons, that connect the CNS to every other part of the body. The PNS includes motor neurons, mediating voluntary movement; the autonomic nervous system, comprising the sympathetic nervous system and the parasympathetic nervous system, which regulate involuntary functions, and the enteric nervous system, which functions to control the gastrointestinal system.',

"nervesoftheheadandneck": 'Head and neck anatomy focuses on the structures of the head and neck of the human body, including the brain, bones, muscles, blood vessels, nerves, glands, nose, mouth, teeth, tongue, and throat. It is an area frequently studied in depth by surgeons, dentists, dental technicians, and speech language pathologists.',

"nervesoftheupperlimb":'The upper limb or upper extremity is the region in an animal extending from the deltoid region to the hand, including the arm, axilla and shoulder.',

"nervesofthethroax":'The thorax or chest (Greek: θώραξ, Latin: thorax) is a part of the anatomy of humans and various other animals located between the neck and the abdomen.[1][2] The thorax includes the thoracic cavity and the thoracic wall. It contains organs including the heart, lungs and thymus gland, as well as muscles and various other internal structures. Many diseases may affect the chest, and one of the most common symptoms is chest pain.',

"nervesofthepelvis":'In human anatomy, the pelvis (plural pelves or pelvises) is either the lower part of the trunk,[1] between the abdomen and the thighs (sometimes also called pelvic region of the trunk), or the skeleton embedded in it[2] (sometimes also called bony pelvis, or pelvic skeleton).',

"nervesofthelowerlimb":'The human leg is the entire lower extremity or limb[1][2] of the human body, including the foot, thigh and even the hip or gluteal region; however, the precise definition in human anatomy refers[3][4][5] only to the section of the lower limb extending from the knee to the ankle (called "crus" in Latin or "sura" for the backpart).',

"reproductivesystem":'The reproductive system or genital system is a system of sex organs within an organism which work together for the purpose of sexual reproduction. Many non-living substances such as fluids, hormones, and pheromones are also important accessories to the reproductive system.[1] Unlike most organ systems, the sexes of differentiated species often have significant differences. These differences allow for a combination of genetic material between two individuals, which allows for the possibility of greater genetic fitness of the offspring.',

"breasts":'The breast is the upper ventral region of the torso of a primate, in left and right sides, containing the mammary gland which in a female can secrete milk used to feed infants.',

"femaleinternalgenitalia":'The female reproductive system (or female genital system) contains two main parts: the uterus, which hosts the developing fetus, produces vaginal and uterine secretions, and can pass sperm through to the Fallopian tubes; and the ovaries, which produce the female"s egg cells. These parts are internal; the vagina meets the external organs at the vulva, which includes the labia, clitoris and urethra. The vagina is attached to the uterus through the cervix, while the uterus is attached to the ovaries via the Fallopian tubes. At certain intervals, the ovaries release an ovum, which passes through the Fallopian tube into the uterus. If, in this transit, it meets with sperm, a single sperm can enter and merge with the egg, fertilizing it. Corresponding equivalent among males is the male reproductive system.',

"uterus":'The uterus (from Latin "uterus", plural uteri) or womb is a major female hormone-responsive reproductive sex organ of most mammals, including humans. One end, the cervix, opens into the vagina, while the other is connected to one or both fallopian tubes, depending on the species. It is within the uterus that the fetus develops during gestation, usually developing completely in placental mammals such as humans and partially in marsupials such as kangaroos and opossums. Two uteri usually form initially in a female and usually male fetus, and in placental mammals they may partially or completely fuse into a single uterus depending on the species. In many species with two uteri, only one is functional. Humans and other higher primates such as chimpanzees, usually have a single completely fused uterus, although in some individuals the uteri may not have completely fused. Horses, on the other hand, have bipartite uteri. In English, the term uterus is used consistently within the medical and related professions, while the Germanic-derived term womb is more common in everyday usage.[citation needed].',

"cervixofuterus":'The cervix or cervix uteri (Latin: neck of the uterus) is the lower part of the uterus in the human female reproductive system. In a non-pregnant woman, the cervix is usually between 2 and 3 cm long and roughly cylindrical in shape. The narrow, central cervical canal runs along its entire length, connecting the uterine cavity and the lumen of the vagina. The opening into the uterus is called the internal os and the opening into the vagina is called the external os. The lower part of the cervix, known as the vaginal portion of the cervix (or ectocervix), bulges into the top of the vagina. The cervix has been documented anatomically since at least the time of Hippocrates, over 2,000 years ago.',

"clitoris":'The clitoris (i/"klɪtərɨs/ or i/klɨ"tɔərɨs/) is a female sex organ present in mammals, ostriches and a limited number of other animals. In humans, the visible button-like portion is near the front junction of the labia minora (inner lips), above the opening of the urethra. Unlike the penis, the male homologue (equivalent) to the clitoris, it usually does not contain the distal portion (or opening) of the urethra and is therefore not used for urination. While few animals urinate through the clitoris, the spotted hyena, which has an especially well-developed clitoris, urinates, mates and gives birth via the organ. Some other carnivorous animals, or mammals in particular, such as lemurs and spider monkeys, also have a well-developed clitoris.',


"externalfemalegenitalia":'The vulva (from the Latin vulva, plural vulvae, see etymology) consists of the external genital organs of the female mammal.[1] This article deals with the vulva of the human being, although the structures are similar for other mammals.',


"respiratorysystem":'The respiratory system (called also respiratory apparatus, ventilatory system) is a biological system consisting of specific organs and structures used for the process of respiration in an organism. The respiratory system is involved in the intake and exchange of oxygen and carbon dioxide between an organism and the environment.',

"leftlung":'The lung is the essential respiration organ in many air-breathing animals, including most tetrapods, a few fish and a few snails. In mammals and the more complex life forms, the two lungs are located near the backbone on either side of the heart. Their principal function is to transport oxygen from the atmosphere into the bloodstream, and to release carbon dioxide from the bloodstream into the atmosphere. A large surface area is needed for this exchange of gases which is accomplished by the mosaic of specialized cells that form millions of tiny, exceptionally thin-walled air sacs called alveoli.',

"rightlung":'The lung is the essential respiration organ in many air-breathing animals, including most tetrapods, a few fish and a few snails. In mammals and the more complex life forms, the two lungs are located near the backbone on either side of the heart. Their principal function is to transport oxygen from the atmosphere into the bloodstream, and to release carbon dioxide from the bloodstream into the atmosphere. A large surface area is needed for this exchange of gases which is accomplished by the mosaic of specialized cells that form millions of tiny, exceptionally thin-walled air sacs called alveoli.',

"oralmucosa":'The oral mucosa is the mucous membrane lining the inside of the mouth and consists of stratified squamous epithelium termed oral epithelium and an underlying connective tissue termed lamina propria.[1] The oral cavity has sometimes been described as a mirror that reflects the health of the individual. Changes indicative of disease are seen as alterations in the oral mucosa lining the mouth, which can reveal systemic conditions, such as diabetes or vitamin deficiency, or the local effects of chronic tobacco or alcohol use.',

"sinuses":'Paranasal sinuses are a group of four paired air-filled spaces that surround the nasal cavity (maxillary sinuses), above the eyes (frontal sinuses), between the eyes (ethmoidal sinuses), and behind the ethmoids (sphenoidal sinuses). The sinuses are named for the facial bones in which they are located.',

"trachea":'The trachea, colloquially called windpipe, is a tube that connects the pharynx and larynx to the lungs, allowing the passage of air, and so is present in all air-breathing animals with lungs. Only in the lungfish, where the lung is connected to the pharynx and the larynx, it is absent.[citation needed] The trachea extends from the larynx and branches into the two primary bronchi. At the top of the trachea the cricoid cartilage attaches it to the larynx. This is the only complete ring, the others being incomplete rings of reinforcing cartilage. The trachealis muscle joins the ends of the rings and these are joined vertically by bands of fibrous connective tissue, the annular ligaments of trachea. The epiglottis closes the opening to the larynx during swallowing.',


"skeletalsystem": 'The human skeleton is the internal framework of the body. It is composed of 270 bones at birth – this total decreases to 206 bones by adulthood after some bones have fused together.[1] The bone mass in the skeleton reaches maximum density around age 30. The human skeleton can be divided into the axial skeleton and the appendicular skeleton. The axial skeleton is formed by the vertebral column, the rib cage and the skull. The appendicular skeleton, which is attached to the axial skeleton, is formed by the pectoral girdle, the pelvic girdle and the bones of the upper and lower limbs.',


"bonesofthehead": 'A head is the cephalic part of an organism, which usually comprises the eyes, ears, nose and mouth, each of which aid in various sensory functions, such as sight, hearing, smell, and taste. Some very simple animals may not have a head, but many bilaterally symmetric forms do. Heads develop in animals by an evolutionary trend known as cephalization. In bilaterally symmetrical animals, nerve tissues concentrate at the anterior region, forming structures responsible for information processing. Through biological evolution, sense organs and feeding structures also concentrate into the interior region; these collectively form the head.',

"bonesoftheupperlimb": 'The upper limb or upper extremity is the region in an animal extending from the deltoid region to the hand, including the arm, axilla and shoulder.',

"bonesofthethorax": 'The thorax or chest (Greek: θώραξ, Latin: thorax) is a part of the anatomy of humans and various other animals located between the neck and the abdomen.[1][2] The thorax includes the thoracic cavity and the thoracic wall. It contains organs including the heart, lungs and thymus gland, as well as muscles and various other internal structures. Many diseases may affect the chest, and one of the most common symptoms is chest pain.',

"bonesofthepelvis": 'In human anatomy, the pelvis (plural pelves or pelvises) is either the lower part of the trunk,[1] between the abdomen and the thighs (sometimes also called pelvic region of the trunk), or the skeleton embedded in it[2] (sometimes also called bony pelvis, or pelvic skeleton)',

"bonesofthelowerlimb":'The human leg is the entire lower extremity or limb[1][2] of the human body, including the foot, thigh and even the hip or gluteal region; however, the precise definition in human anatomy refers[3][4][5] only to the section of the lower limb extending from the knee to the ankle (called "crus" in Latin or "sura" for the backpart).',


"urinarysystem": 'The urinary system, also known as the renal system, consists of the two kidneys, ureters, the bladder, and the urethra. Each kidney consists of millions of functional units called nephrons. The purpose of the renal system is to eliminate wastes from the body, regulate blood volume and pressure, control levels of electrolytes and metabolites, and regulate blood pH. The kidneys have extensive blood supply via the renal arteries which leave the kidneys via the renal vein. Following filtration of blood and further processing, wastes (in the form of urine) exit the kidney via the ureters, tubes made of smooth muscle fibers that propel urine towards the urinary bladder, where it is stored and subsequently expelled from the body by urination (voiding). The female and male urinary system are very similar, differing only in the length of the urethra.',

"lefturinarysystem":'The urinary system, also known as the renal system, consists of the two kidneys, ureters, the bladder, and the urethra. Each kidney consists of millions of functional units called nephrons. The purpose of the renal system is to eliminate wastes from the body, regulate blood volume and pressure, control levels of electrolytes and metabolites, and regulate blood pH. The kidneys have extensive blood supply via the renal arteries which leave the kidneys via the renal vein. Following filtration of blood and further processing, wastes (in the form of urine) exit the kidney via the ureters, tubes made of smooth muscle fibers that propel urine towards the urinary bladder, where it is stored and subsequently expelled from the body by urination (voiding). The female and male urinary system are very similar, differing only in the length of the urethra.',

"righturinarysystem":'The urinary system, also known as the renal system, consists of the two kidneys, ureters, the bladder, and the urethra. Each kidney consists of millions of functional units called nephrons. The purpose of the renal system is to eliminate wastes from the body, regulate blood volume and pressure, control levels of electrolytes and metabolites, and regulate blood pH. The kidneys have extensive blood supply via the renal arteries which leave the kidneys via the renal vein. Following filtration of blood and further processing, wastes (in the form of urine) exit the kidney via the ureters, tubes made of smooth muscle fibers that propel urine towards the urinary bladder, where it is stored and subsequently expelled from the body by urination (voiding). The female and male urinary system are very similar, differing only in the length of the urethra.',

"bladder":'The urinary bladder is the organ that collects urine excreted by the kidneys before disposal by urination. A hollow[1] muscular, and distensible (or elastic) organ, the bladder sits on the pelvic floor. Urine enters the bladder via the ureters and exits via the urethra. There is no exact measurement for the volume of the human bladder, but different sources mention 500 mL (~17 oz) to 1000 mL (~34 oz).',

"muscularsystem":
'The muscular system is an organ system consisting of skeletal, smooth and cardiac muscles. It permits movement of the body, maintains posture, and circulates blood throughout the body. The muscular system in vertebrates is controlled through the nervous system, although some muscles (such as the cardiac muscle) can be completely autonomous. Together with the skeletal system it forms the musculoskeletal system, which is responsible for movement of the human body.',

"musclesoftheheadandneck":
'Head and neck anatomy focuses on the structures of the head and neck of the human body, including the brain, bones, muscles, blood vessels, nerves, glands, nose, mouth, teeth, tongue, and throat. It is an area frequently studied in depth by surgeons, dentists, dental technicians, and speech language pathologists.',

"musclesoftheupperlimb":
'The upper limb or upper extremity is the region in an animal extending from the deltoid region to the hand, including the arm, axilla and shoulder.',

"musclesofthethroax":
'The thorax or chest (Greek: ???a?, Latin: thorax) is a part of the anatomy of humans and various other animals located between the neck and the abdomen.[1][2] The thorax includes the thoracic cavity and the thoracic wall. It contains organs including the heart, lungs and thymus gland, as well as muscles and various other internal structures. Many diseases may affect the chest, and one of the most common symptoms is chest pain.',

"musclesoftheback":
'The human back is the large posterior area of the human body, rising from the top of the buttocks to the back of the neck and the shoulders. It is the surface opposite to the chest, its height being defined by the vertebral column (commonly referred to as the spine or backbone) and its breadth being supported by the ribcage and shoulders. The spinal canal runs through the spine and provides nerves to the rest of the body.',

"musclesoftheabdomen":
'Abdomen (less formally called the belly, stomach, tummy or midriff) constitutes the part of the body between the thorax (chest) and pelvis: in humans and in other vertebrates such as mammals. The region enclosed by the abdomen is termed the abdominal cavity. In arthropods it is the posterior tagma of the body; it follows the thorax or cephalothorax.[1][2] Anatomically, the abdomen stretches from the thorax at the thoracic diaphragm to the pelvis at the pelvic brim. The pelvic brim stretches from the lumbosacral angle (the intervertebral disk between L5 and S1) to the pubic symphysis and is the edge of the pelvic inlet. The space above this inlet and under the thoracic diaphragm is termed the abdominal cavity. The boundary of the abdominal cavity is the abdominal wall in the front and the peritoneal surface at the rear.',

"musclesofthepelvis":
'In human anatomy, the pelvis (plural pelves or pelvises) is either the lower part of the trunk,[1] between the abdomen and the thighs (sometimes also called pelvic region of the trunk), or the skeleton embedded in it[2] (sometimes also called bony pelvis, or pelvic skeleton).',

"musclesofthelowerlimb":
'The human leg is the entire lower extremity or limb[1][2] of the human body, including the foot, thigh and even the hip or gluteal region; however, the precise definition in human anatomy refers[3][4][5] only to the section of the lower limb extending from the knee to the ankle (called "crus" in Latin or "sura" for the backpart).',

"integumentarysystem":
'The integumentary system is the organ system that protects the body from various kinds of damage, such as loss of water or abrasion from outside.[1] The system comprises the skin and its appendages[2][3] (including hair, scales, feathers, hooves, and nails). The integumentary system has a variety of functions; it may serve to waterproof, cushion, and protect the deeper tissues, excrete wastes, and regulate temperature, and is the attachment site for sensory receptors to detect pain, sensation, pressure, and temperature. In most terrestrial vertebrates with significant exposure to sunlight, the integumentary system also provides for vitamin D synthesis.',

"skinoftheheadandneck":
'Head and neck anatomy focuses on the structures of the head and neck of the human body, including the brain, bones, muscles, blood vessels, nerves, glands, nose, mouth, teeth, tongue, and throat. It is an area frequently studied in depth by surgeons, dentists, dental technicians, and speech language pathologists.',

"skinoftheleftarm":
'In human anatomy, the arm is the upper limb of the body, comprising regions between the glenohumeral joint (shoulder joint) and the elbow joint. In common usage the arm extends to the hand. It can be divided into the upper arm (brachium), the forearm (ante brachium), and the hand (manus). Anatomically the shoulder girdle with bones and corresponding muscles is by definition a part of the arm. The Latin term brachium may refer to both the arm as a whole or to the upper arm on its own.',

"skinoftherightarm":
'In human anatomy, the arm is the upper limb of the body, comprising regions between the glenohumeral joint (shoulder joint) and the elbow joint. In common usage the arm extends to the hand. It can be divided into the upper arm (brachium), the forearm (ante brachium), and the hand (manus). Anatomically the shoulder girdle with bones and corresponding muscles is by definition a part of the arm. The Latin term brachium may refer to both the arm as a whole or to the upper arm on its own.',

"skinofthethorax":
'The thorax or chest (Greek: ???a?, Latin: thorax) is a part of the anatomy of humans and various other animals located between the neck and the abdomen.[1][2] The thorax includes the thoracic cavity and the thoracic wall. It contains organs including the heart, lungs and thymus gland, as well as muscles and various other internal structures. Many diseases may affect the chest, and one of the most common symptoms is chest pain.',

"skinofthepelvis":
'In human anatomy, the pelvis (plural pelves or pelvises) is either the lower part of the trunk,[1] between the abdomen and the thighs (sometimes also called pelvic region of the trunk), or the skeleton embedded in it[2] (sometimes also called bony pelvis, or pelvic skeleton).',

"skinoftheleftleg":
'A leg is a weight bearing and locomotive structure, usually having a columnar shape. During locomotion, legs function as "extensible struts".[1] The combination of movements at all joints can be modeled as a single, linear element capable of changing length and rotating about an omnidirectional "hip" joint.',

"skinoftherightleg":
'A leg is a weight bearing and locomotive structure, usually having a columnar shape. During locomotion, legs function as "extensible struts".[1] The combination of movements at all joints can be modeled as a single, linear element capable of changing length and rotating about an omnidirectional "hip" joint.',

"hair":
'Hair is a protein filament that grows from follicles found in the dermis, or skin. Hair is one of the defining characteristics of mammals. The human body, apart from areas of glabrous skin, is covered in follicles which produce thick terminal and fine vellus hair. Most common interest in hair is focused on hair growth, hair types and hair care, but hair is also an important biomaterial primarily composed of protein, notably keratin. Attitudes towards hair, such as hairstyles and hair removal, vary widely across different cultures and historical periods, but it is often used to indicate a person"s personal beliefs or social position, such as their age, gender, or religion.',

"shirt":
'A shirt is a cloth garment for the upper body. Originally an undergarment worn exclusively by men, it has become, in American English, a catch-all term for a broad variety of upper-body garments and undergarments. In British English, a shirt is more specifically a garment with a collar, sleeves with cuffs, and a full vertical opening with buttons or snaps (North Americans would call that a "dress shirt", a specific type of "collared shirt"). A shirt can also be worn with a necktie under the shirt collar.',

"pants":
'Trousers (pants in North America and Australia) are an item of clothing worn from the waist to the ankles, covering both legs separately (rather than with cloth extending across both legs as in robes, skirts, and dresses). In the UK the word "pants" generally means underwear and not trousers.[1] Shorts are similar to trousers, but with legs that come down only to around the area of the knee, higher or lower depending on the style of the garment. To distinguish them from shorts, trousers may be called "long trousers" in certain contexts such as school uniform, where tailored shorts may be called "short trousers", especially in the UK.',
"visceraandfascia":'A fascia ("fæʃə", "fæʃiə"; plural fasciae ; adjective or fascial; from Latin: "band") is connective tissue fibers, primarily collagen, that form sheets or bands beneath the skin to attach, stabilize, enclose, and separate muscles and other internal organs.[1] Fasciae are classified according to their distinct layers, their functions and their anatomical location: superficial fascia, deep (or muscle) fascia, and visceral (or parietal) fascia.',

"leftsubdeltoidbursa":'Bursa is a large city in Turkey, located in northwestern Anatolia, within the Marmara Region. It is the fourth most populous city in Turkey and one of the most industrialized metropolitan centers in the country. The city is also the administrative center of Bursa Province.',

"rightsubdeltoidbursa":'Bursa is a large city in Turkey, located in northwestern Anatolia, within the Marmara Region. It is the fourth most populous city in Turkey and one of the most industrialized metropolitan centers in the country. The city is also the administrative center of Bursa Province.',

"leftolecranonbursa":'Olecranon bursitis (also informally known as "elbow bump",[1] "students elbow", "popeye"s elbow", "Cilentos Disgrace", or "bakers elbow", is a condition characterized by pain, redness and swelling around the olecranon, caused by inflammation of the elbows bursa. This bursa is located just over the extensor aspect of the extreme proximal end of the ulna. In common with other bursae, it is impalpable and contains only a very small amount of fluid in its normal state, and fulfills the function of facilitating the joint"s movement by enabling anatomical structures to glide more easily over each other.',

"rightolecranonbursa":'Olecranon bursitis (also informally known as "elbow bump",[1] "students elbow", "popeyes elbow", "Cilentos Disgrace", or "bakers elbow", is a condition characterized by pain, redness and swelling around the olecranon, caused by inflammation of the elbows bursa. This bursa is located just over the extensor aspect of the extreme proximal end of the ulna. In common with other bursae, it is impalpable and contains only a very small amount of fluid in its normal state, and fulfills the function of facilitating the joints movement by enabling anatomical structures to glide more easily over each other.',

"rightbreastfat":'Fat is one of the three main macronutrients: fat, carbohydrate, and protein.[1] Fats are a wide group of compounds whose basis is in long-chain organic acids, called fatty acids. More particularly fats are esters of such organic acids formed with the alcohol glycerol. Glycerol is a triol, meaning that it has three chemically active -OH (hydroxyl) groups. Fats are made when each of these three -OH groups reacts with a fatty acid. The resulting fats are called triglycerides. Because of their preponderant aliphatic structure, fats are hydrophobic, generally soluble in organic solvents but generally insoluble in water. Fats made up of shorter chain fatty acids are usually liquid at room temperature, whereas the longer chain fats will be solid. Some ambiguity in terminology arises because the words "oil", "fat", and "lipid" are often used interchangeably. Of these lipid[2] is the general term, because a lipid is not necessarily a triglyceride. Oil is the term usually used to refer to fats that are liquids at normal room temperature, while fat is usually used to refer to fats that are solids at normal room temperature.',

"leftbreastfat":'Fat is one of the three main macronutrients: fat, carbohydrate, and protein.[1] Fats are a wide group of compounds whose basis is in long-chain organic acids, called fatty acids. More particularly fats are esters of such organic acids formed with the alcohol glycerol. Glycerol is a triol, meaning that it has three chemically active -OH (hydroxyl) groups. Fats are made when each of these three -OH groups reacts with a fatty acid. The resulting fats are called triglycerides. Because of their preponderant aliphatic structure, fats are hydrophobic, generally soluble in organic solvents but generally insoluble in water. Fats made up of shorter chain fatty acids are usually liquid at room temperature, whereas the longer chain fats will be solid. Some ambiguity in terminology arises because the words "oil", "fat", and "lipid" are often used interchangeably. Of these lipid[2] is the general term, because a lipid is not necessarily a triglyceride. Oil is the term usually used to refer to fats that are liquids at normal room temperature, while fat is usually used to refer to fats that are solids at normal room temperature.',

"rightvisceralpleura":'Each lung is invested by an exceedingly delicate serous membrane, the pleura, which is arranged in the form of a closed invaginated sac. A portion of the serous membrane covers the surface of the lung and dips into the fissures between its lobes; it is called the visceral pleura or (pulmonary pleura). The visceral pleura is derived from mesoderm.',

"leftvisceralpleura":'Each lung is invested by an exceedingly delicate serous membrane, the pleura, which is arranged in the form of a closed invaginated sac. A portion of the serous membrane covers the surface of the lung and dips into the fissures between its lobes; it is called the visceral pleura or (pulmonary pleura). The visceral pleura is derived from mesoderm.',

"rightparietalpleura":'The parietal pleura is the part of the pleura external to the visceral pleura. It lines the inner surface of the chest wall, covers the diaphragm, and is reflected over the structures occupying the middle of the thorax.',

"leftparietalpleura":'The parietal pleura is the part of the pleura external to the visceral pleura. It lines the inner surface of the chest wall, covers the diaphragm, and is reflected over the structures occupying the middle of the thorax.',

"mesoappemdix":'The mesentery is a fold of membranous tissue that arises from the posterior wall of the peritoneal cavity and attaches to the intestinal tract. Within it are the arteries and veins that supply the intestine. The term can be used narrowly to denote just the material that supplies the jejunum and ileum of the small intestine, or broadly to include the right, left and transverse mesocolon, mesoappendix, mesosigmoid and mesorectum.',

"mesenteryofsmallintestine":'The small intestine (or small bowel) is the part of the GI tract following the stomach and followed by the large intestine, and is where much of the digestion and absorption of food takes place. The small intestine is composed of a duodenum, jejunum, and ileum. It receives bile juice and pancreatic juice through the pancreatic duct, controlled by the sphincter of Oddi.',


"greateromentum":'The greater omentum (also the great omentum, omentum majus, gastrocolic omentum, epiploon, or, especially in animals, caul) is a large apron-like fold of visceral peritoneum that hangs down from the stomach. It extends from the greater curvature of the stomach, passing in front of the small intestines and reflects on itself to ascend to the transverse colon before reaching to the posterior abdominal wall. The common anatomical term "epiploic" derives from "epiploon" from the Greek "epipleein" meaning to float or sail on, since the greater omentum appears to float on the surface of the intestines. It is the first structure observed when the abdominal cavity is opened anteriorly.',

"mesocolon":'The adult female anatomy',

"epiploicappendagesofcolon":'The adult female anatomy',




	};

	window.bodyinfo = bodydata;

})(window);